"use client";

import { ChevronLeft, ChevronRight, Clock3 } from "lucide-react";
import { useState } from "react";
import { todaysAppointments } from "../../dashboard/data";
import { AppointmentAvatar } from "../../dashboard/components/AppointmentAvatar";

const dates = Array.from({ length: 30 }, (_, index) => index + 1);
export function CalendarClient() { const [selected, setSelected] = useState(12); return <div className="mt-7 grid gap-6 xl:grid-cols-[1.55fr_0.8fr]"><section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><div className="mb-7 flex items-center justify-between"><button aria-label="Previous month" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-500"><ChevronLeft size={18} /></button><h2 className="font-bold text-slate-800">September 2026</h2><button aria-label="Next month" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-500"><ChevronRight size={18} /></button></div><div className="grid grid-cols-7 text-center text-xs font-bold uppercase tracking-wide text-slate-400">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day} className="pb-4">{day}</span>)}</div><div className="grid grid-cols-7 gap-y-2">{Array.from({ length: 1 }, (_, i) => <span key={`blank-${i}`} />)}{dates.map((date) => { const hasAppointment = [12, 13, 14, 15, 18, 21].includes(date); const active = date === selected; return <button key={date} onClick={() => setSelected(date)} className="mx-auto flex h-10 w-10 flex-col items-center justify-center rounded-xl text-sm font-semibold text-slate-600 transition hover:bg-teal-50"><span className={`grid h-8 w-8 place-items-center rounded-lg ${active ? "bg-brand text-white shadow-md shadow-teal-900/15" : ""}`}>{date}</span>{hasAppointment && <i className={`h-1 w-1 rounded-full ${active ? "bg-white" : "bg-brand"}`} />}</button>; })}</div></section><aside className="rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><p className="text-sm font-medium text-brand">Saturday, 12 September</p><h2 className="mt-2 text-xl font-bold text-slate-800">{selected === 12 ? "Today’s schedule" : `Schedule · ${selected} September`}</h2><div className="mt-6 space-y-4">{todaysAppointments.map((appointment) => <div key={appointment.id} className="flex gap-3 border-l-2 border-brand pl-3"><p className="w-14 pt-1 text-xs font-bold text-slate-500">{appointment.time}</p><div className="flex min-w-0 flex-1 items-center gap-2"><AppointmentAvatar initials={appointment.initials} color={appointment.color} size="sm" /><div><p className="text-sm font-semibold text-slate-700">{appointment.patient}</p><p className="mt-0.5 text-xs text-slate-400">{appointment.reason}</p></div></div></div>)}</div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-teal-50 py-3 text-sm font-bold text-brand"><Clock3 size={16} />View daily schedule</button></aside></div>; }
