"use client";

import { CalendarDays, ChevronDown, MoreHorizontal, Search } from "lucide-react";
import { useMemo, useState } from "react";
import type { Appointment, AppointmentStatus } from "../../dashboard/types";
import { AppointmentAvatar } from "../../dashboard/components/AppointmentAvatar";

const filters: ("All" | AppointmentStatus)[] = ["All", "Pending", "Confirmed", "Completed"];
export function BookingsClient({ bookings }: { bookings: Appointment[] }) {
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");
  const [query, setQuery] = useState("");
  const visible = useMemo(() => bookings.filter((b) => (filter === "All" || b.status === filter) && b.patient.toLowerCase().includes(query.toLowerCase())), [filter, query, bookings]);
  return <><div className="mt-7 flex flex-col gap-4 rounded-2xl border border-slate-100 bg-white p-4 shadow-card sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 overflow-x-auto pb-1 sm:pb-0">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${filter === item ? "bg-brand text-white" : "text-slate-500 hover:bg-slate-50"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-slate-400 sm:w-64"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm text-slate-700 outline-none" placeholder="Search patient..." /></label></div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-card"><div className="hidden grid-cols-[1.6fr_1.1fr_1.25fr_0.9fr_36px] gap-4 border-b border-slate-100 px-6 py-4 text-xs font-bold uppercase tracking-wide text-slate-400 lg:grid"><span>Patient</span><span>Date</span><span>Reason</span><span>Status</span><span /></div><div className="divide-y divide-slate-100">{visible.map((booking) => <article key={booking.id} className="grid gap-3 px-5 py-4 lg:grid-cols-[1.6fr_1.1fr_1.25fr_0.9fr_36px] lg:items-center lg:gap-4 lg:px-6"><div className="flex items-center gap-3"><AppointmentAvatar initials={booking.initials} color={booking.color} size="sm" /><div><p className="text-sm font-semibold text-slate-700">{booking.patient}</p><p className="mt-0.5 text-xs text-slate-400">{booking.id} · {booking.age} yrs</p></div></div><p className="flex items-center gap-1.5 text-sm text-slate-500"><CalendarDays size={15} className="text-brand" />{booking.date ?? "Today"} · {booking.time}</p><p className="text-sm text-slate-500">{booking.reason}</p><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${booking.status === "Pending" ? "bg-amber-50 text-amber-600" : booking.status === "Completed" ? "bg-slate-100 text-slate-500" : "bg-emerald-50 text-emerald-600"}`}>{booking.status}</span><button aria-label={`More options for ${booking.patient}`} className="text-slate-400"><MoreHorizontal size={20} /></button></article>)}{!visible.length && <p className="px-6 py-12 text-center text-sm text-slate-400">No appointments found.</p>}</div></section></>;
}
